In [ ]:
#q1
# Importing the modules and loading the dataset.
import pandas as pd

In [ ]:
df = pd.read_csv("/content/Data for Project 1 (1).csv")
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [ ]:
# Get the dataset information using the 'info()' function.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [ ]:
#q2
# Check for the null values in all the columns using 'df.isnull().sum()'.
df.isnull().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [ ]:
# Remove the rows/columns containing the null values .
df = data.dropna()
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [ ]:
# Convert the data-type of the year values into integer values.
df["Year"].apply(int)

0        2006
1        1985
2        2008
3        2009
4        1996
         ...
16593    2002
16594    2003
16595    2008
16596    2010
16597    2003
Name: Year, Length: 16291, dtype: int64

In [ ]:
#q3
# Find out the total number of units sold yearly across different regions and the world.
 # store the number of units sold yearly in a variable (let's say 'group_year').

 # Get the total units sold from last 5 columns.
last = df.tail(5)
last[['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']].sum()
last

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.0,0.0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.0,0.0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.0,0.0,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.0,0.0,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.0,0.0,0.01

In [ ]:
NA = df['NA_Sales'].sum()
EU = df['EU_Sales'].sum()
JP = df['JP_Sales'].sum()
OT = df['Other_Sales'].sum()
GL = df['Global_Sales'].sum()
sales = [NA,EU,JP,OT,GL]
group_year = pd.DataFrame(sales, columns = ['sales'])
group_year

     sales
0  4327.65
1  2406.69
2  1284.27
3   788.91
4  8811.97

In [ ]:
# Create the line plots for the total number of units sold yearly across different regions and the world.

In [ ]:
# In which year, the most number of games were sold global)]
a = df[['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']]
b = a.sum(axis = 1)
c = b.max()
c

165.48000000000002

In [ ]:
#q4
# Find out the genre-wise total number of units sold across different regions and the world.
df.groupby(['Genre'])[['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']].sum()

              NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
Genre
Action          861.77    516.48    158.65       184.92       1722.84
Adventure       101.93     63.74     51.99        16.70        234.59
Fighting        220.74    100.00     87.15        36.19        444.05
Misc            396.92    211.77    106.67        73.92        789.87
Platform        445.99    200.65    130.65        51.51        829.13
Puzzle          122.01     50.52     56.68        12.47        242.21
Racing          356.93    236.31     56.61        76.68        726.76
Role-Playing    326.50    187.57    350.29        59.38        923.83
Shooter         575.16    310.45     38.18       101.90       1026.20
Simulation      181.78    113.02     63.54        31.36        389.98
Sports          670.09    371.34    134.76       132.65       1309.24
Strategy         67.83     44.84     49.10        11.23        173.27

In [ ]:
# Create line plots for genre-wise total number of units sold across different regions and the world

In [ ]:
# What genre of video game is most popular in Japan in terms of the total number of units sold?

In [ ]:
# Genre-wise total number of units sold across different regions and the world in descending order.
 # Get the total units sold from last 5 columns.
# Sort the values in descending order
df.sort_values("Global_Sales",ascending = False)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16183,16186,Sakura-Sou no Pet na Kanojo,PSP,2013.0,Adventure,Kadokawa Games,0.00,0.00,0.01,0.00,0.01
16184,16187,Fatal Fury: Battle Archives Volume 2 (JP sales),PS2,2007.0,Fighting,SNK Playmore,0.00,0.00,0.01,0.00,0.01
16185,16188,Tantei Jinguuji Saburo: Hai to Diamond,PSP,2009.0,Adventure,Arc System Works,0.00,0.00,0.01,0.00,0.01
16186,16189,BattleForge,PC,2009.0,Strategy,Electronic Arts,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [ ]:
a1 = df[['Genre','NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']]

In [ ]:
#q5
# Publisher-wise total number of units sold across different regions and the world in descending order.
 # Get the total units sold from last 5 columns.
# Sort the values in descending order
df.tail(5)[['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']].sum()

NA_Sales        0.03
EU_Sales        0.01
JP_Sales        0.00
Other_Sales     0.00
Global_Sales    0.05
dtype: float64

In [ ]:
df.sort_values("Publisher",ascending = False)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
10945,10947,Yourself Fitness,XB,2004.0,Sports,responDESIGN,0.07,0.02,0.00,0.00,0.09
13684,13686,Yourself Fitness,PS2,2005.0,Sports,responDESIGN,0.02,0.02,0.00,0.01,0.04
2409,2411,Monster Strike 3DS,3DS,2015.0,Action,"mixi, Inc",0.00,0.00,0.86,0.00,0.86
10756,10758,Wasteland 2,PC,2015.0,Role-Playing,inXile Entertainment,0.02,0.06,0.00,0.01,0.10
16423,16426,SoniPro,3DS,2014.0,Adventure,imageepoch Inc.,0.00,0.00,0.01,0.00,0.01
...,...,...,...,...,...,...,...,...,...,...,...
13057,13059,Men of War: Assault Squad,PC,2011.0,Strategy,1C Company,0.01,0.03,0.00,0.01,0.05
13724,13726,Off-Road Drive,PC,2011.0,Racing,1C Company,0.00,0.03,0.00,0.01,0.04
15706,15709,Pirates: Legend of the Black Buccaneer,PS2,2006.0,Adventure,10TACLE Studios,0.01,0.01,0.00,0.00,0.02
14130,14132,Boulder Dash: Rocks!,DS,2007.0,Puzzle,10TACLE Studios,0.00,0.03,0.00,0.00,0.03
12349,12351,Panzer Tactics,DS,2007.0,Strategy,10TACLE Studios,0.06,0.00,0.00,0.00,0.06

In [ ]:
df.groupby(['Publisher'])[['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']].sum()

,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Publisher,,,,,
10TACLE Studios,0.07,0.04,0.00,0.00,0.11
1C Company,0.01,0.07,0.00,0.02,0.10
20th Century Fox Video Games,1.82,0.10,0.00,0.01,1.94
2D Boy,0.00,0.03,0.00,0.01,0.04
3DO,6.48,3.04,0.00,0.63,10.12
...,...,...,...,...,...
id Software,0.02,0.00,0.00,0.00,0.03
imageepoch Inc.,0.00,0.00,0.04,0.00,0.04
inXile Entertainment,0.02,0.06,0.00,0.01,0.10
"mixi, Inc",0.00,0.00,0.86,0.00,0.86
responDESIGN,0.09,0.04,0.00,0.01,0.13

In [ ]:
#q6
# Find out the platform-wise the total number of units sold across different regions and the world in the descending order.
 # Get the total units sold from last 5 columns.
# Sort the values in descending order

In [ ]:
df.sort_values("Platform",ascending = False)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
15052,15055,NASCAR Heat Evolution,XOne,2016.0,Racing,Dusenberry Martin Racing,0.02,0.00,0.00,0.00,0.02
12579,12581,TrackMania Turbo,XOne,2016.0,Action,Ubisoft,0.02,0.03,0.00,0.00,0.06
11305,11307,Dead or Alive 5,XOne,2015.0,Fighting,Tecmo Koei,0.04,0.03,0.01,0.01,0.08
1605,1607,The Witcher 3: Wild Hunt,XOne,2015.0,Role-Playing,Namco Bandai Games,0.66,0.47,0.00,0.11,1.24
13174,13176,MXGP 2,XOne,2016.0,Racing,Milestone S.r.l.,0.02,0.02,0.00,0.00,0.05
...,...,...,...,...,...,...,...,...,...,...,...
1163,1165,Mario Bros.,2600,1982.0,Platform,Atari,1.48,0.09,0.00,0.02,1.59
1153,1155,River Raid,2600,1981.0,Shooter,Activision,1.49,0.09,0.00,0.02,1.60
5366,5368,Freeway,2600,1980.0,Action,Activision,0.32,0.02,0.00,0.00,0.34
5381,5383,Alien's Return,2600,1982.0,Action,ITT Family Games,0.32,0.02,0.00,0.00,0.34
7904,7906,International Soccer,2600,1981.0,Sports,Mattel Interactive,0.18,0.01,0.00,0.00,0.19

In [ ]:
df.groupby(['Platform'])[['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']].sum()

          NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
Platform
2600         80.78      4.86      0.00         0.84         86.57
3DO           0.00      0.00      0.10         0.00          0.10
3DS          78.03     58.29     97.30        12.55        246.27
DC            5.43      1.69      8.56         0.27         15.97
DS          388.53    194.05    175.02        60.29        818.91
GB          113.64     47.51     85.12         8.16        254.42
GBA         178.43     72.49     46.56         7.51        305.62
GC          131.94     38.32     21.34         5.13        197.14
GEN          19.27      5.52      2.67         0.89         28.36
GG            0.00      0.00      0.04         0.00          0.04
N64         138.91     41.03     33.76         4.31        218.21
NES         125.94     21.15     98.65         5.31        251.07
NG            0.00      0.00      1.44         0.00          1.44
PC           92.04    137.35      0.17        24.33        254.70
PCFX          0.00      0.00      0.03         0.00          0.03
PS          334.71    212.38    139.78        40.69        727.39
PS2         572.92    332.63    137.54       190.47       1233.46
PS3         388.90    340.47     79.21       140.81        949.35
PS4          96.80    123.70     14.30        43.36        278.10
PSP         107.09     67.16     75.89        41.52        291.71
PSV          16.07     16.27     20.86         8.41         61.60
SAT           0.72      0.54     32.26         0.07         33.59
SCD           1.00      0.36      0.45         0.05          1.87
SNES         61.23     19.04    116.55         3.22        200.05
TG16          0.00      0.00      0.16         0.00          0.16
WS            0.00      0.00      1.42         0.00          1.42
Wii         497.37    264.35     68.28        79.20        909.81
WiiU         38.32     24.23     12.79         6.45         81.86
X360        594.33    278.00     12.30        84.67        969.60
XB          182.06     59.65      1.38         8.48        252.09
XOne         83.19     45.65      0.34        11.92        141.06